//
//  PYInterflowParams.m
//  PYInterflow
//
//  Created by wlpiaoyi on 2016/12/7.
//  Copyright © 2016年 wlpiaoyi. All rights reserved.
//

#import "PYInterflowParams.h"
#import "PYUtile.h"
#import "PYPopupParam.h"

void * _Nonnull PY_OBJ_OrgWindow;

void (^BlockDialogButtonStyle)(UIButton * _Nonnull button);
BOOL STATIC_POPUP_HASEFFECT = NO;
CGFloat PYPopupEffectCpuUsage = .05;
CGFloat PYPopupAnimationTime = 10.0;
CGFloat PYPopupAnimationTimeOffset = .05;

UIColor * _Nonnull STATIC_CONTENT_BACKGROUNDCLOLOR;
UIColor * _Nonnull STATIC_DIALOG_BACKGROUNDCLOLOR;
UIColor * _Nonnull STATIC_DIALOG_BORDERCLOLOR;
UIColor * _Nonnull STATIC_DIALOG_TEXTCLOLOR;
UIFont * _Nonnull STATIC_DIALOG_TITLEFONT;
UIFont * _Nonnull STATIC_DIALOG_MESSAGEFONT;
UIFont * _Nonnull STATIC_DIALOG_BUTTONFONT;
CGFloat STATIC_DIALOG_OFFSETBORDER = 20;
CGFloat STATIC_DIALOG_MINWIDTH = 260;
CGFloat STATIC_DIALOG_MAXWIDTH = 300;
CGFloat STATIC_DIALOG_MAXHEIGHT = 400;
CGFloat STATIC_DIALOG_BORDERWIDTH = .5;
CGFloat STATIC_DIALOG_WIDTH = 280;
CGFloat STATIC_DIALOG_OFFSETWIDTH = 2;
CGFloat STATIC_DIALOG_TITLE_HEIGHT = 44;
CGFloat STATIC_DIALOG_BUTTON_HEIGHT = 44;


UIColor * _Nonnull STATIC_SHEET_TITLEC;
UIColor * _Nonnull STATIC_SHEET_TITLEBGC;
UIColor * _Nonnull STATIC_SHEET_CONTEXTNORMALC;
UIColor * _Nonnull STATIC_SHEET_CONTEXTNORMALBGC;
UIColor * _Nonnull STATIC_SHEET_CONTEXTHIGHTLIGHTC;
UIColor * _Nonnull STATIC_SHEET_CONTEXTHIGHTLIGHTBGC;
UIColor * _Nonnull STATIC_SHEET_CANCELNORMALC;
UIColor * _Nonnull STATIC_SHEET_CANCELNORMALBGC;
UIColor * _Nonnull STATIC_SHEET_CANCELHIGHTLIGHTC;
UIColor * _Nonnull STATIC_SHEET_CANCELHIGHTLIGHTBGC;
UIFont * _Nonnull STATIC_SHEET_TITLEFONT;
UIFont * _Nonnull STATIC_SHEET_CONTEXTFONT;
UIFont * _Nonnull STATIC_SHEET_CANCELFONT;

UIColor * _Nonnull STATIC_TOPBAR_MESSAGEC;
UIColor * _Nonnull STATIC_TOPBAR_BGC;
UIFont * _Nonnull STATIC_TOPBAR_MESSAGEFONT;

NSString * STATIC_POPUP_EFFECTE_NOTIFY = @"pypeffn";
NSString * STATIC_POPUP_SHOW_NOTIFY = @"adsfasdfasdf";
NSString * STATIC_POPUP_HIDEEN_NOTIFY = @"adfkididj";
@implementation PYInterflowParams

+(void) loadInterflowParamsData{
    STATIC_SHEET_TITLEC = [UIColor darkGrayColor];
    STATIC_SHEET_TITLEBGC = [UIColor whiteColor];
    STATIC_SHEET_CONTEXTNORMALC = [UIColor grayColor];
    STATIC_SHEET_CONTEXTNORMALBGC = [UIColor whiteColor];
    STATIC_SHEET_CONTEXTHIGHTLIGHTC = STATIC_SHEET_CONTEXTNORMALBGC;
    STATIC_SHEET_CONTEXTHIGHTLIGHTBGC = STATIC_SHEET_CONTEXTNORMALC;
    STATIC_SHEET_CANCELNORMALC = [UIColor grayColor];
    STATIC_SHEET_CANCELNORMALBGC = [UIColor whiteColor];
    STATIC_SHEET_CANCELHIGHTLIGHTC = STATIC_SHEET_CANCELNORMALBGC;;
    STATIC_SHEET_CANCELHIGHTLIGHTBGC = STATIC_SHEET_CANCELNORMALC;
    STATIC_SHEET_TITLEFONT = [UIFont boldSystemFontOfSize:18];
    STATIC_SHEET_CONTEXTFONT = [UIFont systemFontOfSize:14];
    STATIC_SHEET_CANCELFONT = STATIC_SHEET_CONTEXTFONT;
    STATIC_CONTENT_BACKGROUNDCLOLOR = [UIColor colorWithRed:0 green:0 blue:0 alpha:.3];
    STATIC_DIALOG_BACKGROUNDCLOLOR = [UIColor whiteColor];
    STATIC_DIALOG_BORDERCLOLOR = [UIColor lightGrayColor];
    STATIC_DIALOG_TEXTCLOLOR = [UIColor darkGrayColor];
    STATIC_DIALOG_TITLEFONT = [UIFont systemFontOfSize:18];
    STATIC_DIALOG_MESSAGEFONT = [UIFont italicSystemFontOfSize:14];
    STATIC_DIALOG_BUTTONFONT = [UIFont boldSystemFontOfSize:18];
    
    STATIC_TOPBAR_MESSAGEC = [UIColor colorWithRGBHex:0x000000AA];
    STATIC_TOPBAR_BGC = [UIColor whiteColor];
    STATIC_TOPBAR_MESSAGEFONT = [UIFont systemFontOfSize:14];
    [PYPopupParam RECIRCLE_REFRESH_EFFECT];
}

//+(void) setView:(UIView *) view shadowOffset:(CGSize) size{
//    view.layer.shadowRadius = 3;
//    view.layer.shadowOpacity = 1 ;
//    view.layer.shadowColor = STATIC_DIALOG_BORDERCLOLOR.CGColor;
//    view.layer.shadowOffset = size;
//    view.clipsToBounds = NO;
//}

@end
